export const highlightLanguages = {
  bash: 'Bash',
  basic: 'Basic',
  csharp: 'C#',
  c: 'C',
  cpp: 'C++',
  css: 'CSS',
  dos: 'DOS',
  go: 'Go',
  html: 'HTML',
  json: 'JSON',
  java: 'Java',
  js: 'JavaScript',
  lua: 'Lua',
  php: 'PHP',
  plaintext: 'Plaintext',
  powershell: 'PowerShell',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  scss: 'SCSS',
  shell: 'Shell',
  ts: 'TypeScript',
  zig: 'Zig',
};
